export enum EValuationStatus {
  WAITING_FOR_PAYMENT = "WAITING_FOR_PAYMENT",
  FINDING_VALUER = "FINDING_VALUER",
  VALUER_ASSIGNED = "VALUER_ASSIGNED",
  INSPECTION_SCHEDULED = "INSPECTION_SCHEDULED",
  INSPECTION_COMPLETED = "INSPECTION_COMPLETED",
  VALUATION_SUBMITTED = "VALUATION_SUBMITTED",
}
